[env]
TERM = "xterm-256color"

[window]
padding      = { x = 2, y = 0 }
decorations  = "None"
startup_mode = "Maximized"

[scrolling]
history    = 0
multiplier = 0

[font]
normal      = { family = "FiraCode Nerd Font", style = "Medium" }
bold        = { family = "FiraCode Nerd Font", style = "Bold" }
italic      = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "Menlo", style = "Bold Italic" }
size        = 12.0

[colors]
cursor    = { text = "#feffff", cursor =  "#ff00ff" }
selection = { text = "#000000", background = "#c1ddff" }

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#076678"
magenta = "#b16286"
cyan    = "#0aaeb3"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#b16286"
cyan    = "#5ffdff"
white   = "#ebdbb2"

[terminal]
shell = { program = "/bin/zsh", args = ["--login"] }

[keyboard]
bindings = [
  # the good old mac k-bomb in tmux:
  ## pass this though to tmux as <C-space (tmux leader)>k, in tmux bind <leader>k to C-l and clear-history
  { key = "k", mods = "Command", chars =  "\u0000k" },
  # <C-^> doesn"t seem to work in vim without this remap
  { key = "Key6", mods = "Control", chars = "\u001e" }
  # sending escape sequences for alt is supported but not working on osx, so map manually as needed
  # { key: Period,   mods: Alt,           chars: "\x1b."           }
  # { key: C,        mods: Alt,           chars: "\x1bc" }
]
